
package com.travel.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Sun Apr 17 12:06:40 CEST 2022
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "addDestination", namespace = "http://service.webservice.travel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addDestination", namespace = "http://service.webservice.travel.com/", propOrder = {"id_destination", "name_dest", "type_dest", "id_city", "dest_picture"})

public class AddDestination {

    @XmlElement(name = "id_destination")
    private int id_destination;
    @XmlElement(name = "name_dest")
    private java.lang.String name_dest;
    @XmlElement(name = "type_dest")
    private int type_dest;
    @XmlElement(name = "id_city")
    private int id_city;
    @XmlElement(name = "dest_picture")
    private java.lang.String dest_picture;

    public int getId_destination() {
        return this.id_destination;
    }

    public void setId_destination(int newId_destination)  {
        this.id_destination = newId_destination;
    }

    public java.lang.String getName_dest() {
        return this.name_dest;
    }

    public void setName_dest(java.lang.String newName_dest)  {
        this.name_dest = newName_dest;
    }

    public int getType_dest() {
        return this.type_dest;
    }

    public void setType_dest(int newType_dest)  {
        this.type_dest = newType_dest;
    }

    public int getId_city() {
        return this.id_city;
    }

    public void setId_city(int newId_city)  {
        this.id_city = newId_city;
    }

    public java.lang.String getDest_picture() {
        return this.dest_picture;
    }

    public void setDest_picture(java.lang.String newDest_picture)  {
        this.dest_picture = newDest_picture;
    }

}

